export const lcs = {
  '100': {
    "Ssumday":      { position: 'top' },
    'AnDa':         { position: 'jungle' },
    'Huhi':         { position: 'mid' },
    'Bang':         { position: 'bot' },
    'Aphromoo':     { position: 'supp' },
    'Pr0lly':       { position: 'coach' },
  },
  'c9': {
    'Licorice':     { position: 'top' },
    'Svenskeren':   { position: 'jungle' },
    'Nisqy':        { position: 'mid' },
    'Sneaky':       { position: 'bot' },
    'Zeyzal':       { position: 'supp' },
    'Reapered':     { position: 'coach' },
  },
  'cg': {
    'Huni': { position: 'top' },
    'Lira': { position: 'jungle' },
    'Damonte': { position: 'mid' },
    'Piglet': { position: 'bot' },
    'Vulcan': { position: 'supp' },
    'McScrag': { position: 'coach' },
  },
  'clg': {
    'Darshan': { position: 'top' },
    'Wiggily': { position: 'jungle' },
    'PowerOfEvil': { position: 'mid' },
    'Stixxay': { position: 'bot' },
    'Biofrost': { position: 'supp' },
    'Weldon': { position: 'coach' },
  },
  'fox': {
    'Solo': { position: 'top' },
    'Rush': { position: 'jungle' },
    'Fenix': { position: 'mid' },
    'Apollo': { position: 'bot' },
    'Hakuho': { position: 'supp' },
    'Ssong': { position: 'coach' },
  },
  'fly': {
    'V1per': { position: 'top' },
    'Santorin': { position: 'jungle' },
    'Pobelter': { position: 'mid' },
    'WildTurtle': { position: 'bot' },
    'JayJ': { position: 'supp' },
    'Invert': { position: 'coach' },
  },
  'ggs': {
    'Hauntzer': { position: 'top' },
    'Contractz': { position: 'jungle' },
    'Froggen': { position: 'mid' },
    'Deftly': { position: 'bot' },
    'Olleh': { position: 'supp' },
    'Inero': { position: 'coach' },
  },
  'opt': {
    'Dhokla': { position: 'top' },
    'Meteos': { position: 'jungle' },
    'Crown': { position: 'mid' },
    'Arrow': { position: 'bot' },
    'Big': { position: 'supp' },
    'Zaboutine': { position: 'coach' },
  },
  'tl': {
    'Impact': { position: 'top' },
    'Xmithie': { position: 'jungle' },
    'Jensen': { position: 'mid' },
    'Doublelift': { position: 'bot' },
    'CoreJJ': { position: 'supp' },
    'Cain': { position: 'coach' },
  },
  'tsm': {
    'Broken Blade': { position: 'top' },
    'Akaadian': { position: 'jungle' },
    'Bjergsen': { position: 'mid' },
    'Zven': { position: 'bot' },
    'Smoothie': { position: 'supp' },
    'Zikz': { position: 'coach' },
  },
};
