// import playerDataCSV from './LoLProWinsApp-StaticWinsData.csv';

// export const playersData = () => {
//   const lines = playerDataCSV.split('\n');
//   const lcsProPlayers = [];
//   const headers = lines[0].split(',');

//   for(let i = 1; i < lines.length; i++) {
//     const obj = {};
//     const currentline = lines[i].split(',');

//     for(let j = 0; j < headers.length; j++) {
//       obj[headers[j]] = currentline[j];
//     }

//     lcsProPlayers.push(obj);
//   }

//   return (lcsProPlayers); //JavaScript array
//   // return (JSON.stringify(lcsProPlayers)); //JSON
// }

export const proPlayers = {
  /* ---------------------------------------------
  // 1 through 10
  --------------------------------------------- */
  'Ssumday': {
    'Profile': 'https://lol.gamepedia.com/Ssumday',
    'SoloQueueName': 'Ssumdayday',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Team Dignitas',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
      'SummerWins': 29,
      'SummerTeam': 'Team Dignitas',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
    },
    '2018': {
      'SpringWins': 13,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 12,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'AnDa': {
    'Profile': 'https://lol.gamepedia.com/AnDa',
    'SoloQueueName': 'AnDa',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 6,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': 8,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Huhi': {
    'Profile': 'https://lol.gamepedia.com/Huhi',
    'SoloQueueName': 'huhi',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 7,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Bang': {
    'Profile': 'https://lol.gamepedia.com/Bang',
    'SoloQueueName': '100T Bang',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'SK Telecom T1',
      'SpringTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
      'SummerWins': 26,
      'SummerTeam': 'SK Telecom T1',
      'SummerTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
    },
    '2018': {
      'SpringWins': 23,
      'SpringTeam': 'SK Telecom T1',
      'SpringTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
      'SummerWins': 19,
      'SummerTeam': 'SK Telecom T1',
      'SummerTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Aphromoo': {
    'Profile': 'https://lol.gamepedia.com/Aphromoo',
    'SoloQueueName': 'aphromoo',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 13,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 12,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Licorice': {
    'Profile': 'https://lol.gamepedia.com/Licorice',
    'SoloQueueName': 'Licorice',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 11,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Svenskeren': {
    'Profile': 'https://lol.gamepedia.com/Svenskeren',
    'SoloQueueName': 'Paradiser',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'Team SoloMid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
      'SummerWins': 30,
      'SummerTeam': 'Team SoloMid',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 3,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Nisqy': {
    'Profile': 'https://lol.gamepedia.com/Nisqy',
    'SoloQueueName': 'C9 Nisqyyy',
    '2017': {
      'SpringWins': 5,
      'SpringTeam': 'Team EnVy',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
      'SummerWins': 11,
      'SummerTeam': 'Team EnVy',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Splyce',
      'SpringTeamLink': 'https://lol.gamepedia.com/Splyce',
      'SummerWins': 9,
      'SummerTeam': 'Splyce',
      'SummerTeamLink': 'https://lol.gamepedia.com/Splyce',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Sneaky': {
    'Profile': 'https://lol.gamepedia.com/Sneaky',
    'SoloQueueName': 'C9 Sneaky',
    '2017': {
      'SpringWins': 31,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 28,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 10,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Zeyzal': {
    'Profile': 'https://lol.gamepedia.com/Zeyzal',
    'SoloQueueName': 'Zeyzal',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 11,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 11 through 20
  --------------------------------------------- */
  'Huni': {
    'Profile': 'https://lol.gamepedia.com/Huni',
    'SoloQueueName': 'StrongHuni',
    '2017': {
      'SpringWins': 25,
      'SpringTeam': 'SK Telecom T1',
      'SpringTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
      'SummerWins': 7,
      'SummerTeam': 'SK Telecom T1',
      'SummerTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': 11,
      'SummerTeam': 'Echo Fox',
      'SummerTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
    },
    '2019': {
      'SpringWins': 5,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Lira': {
    'Profile': 'https://lol.gamepedia.com/Lira',
    'SoloQueueName': 'Lira',
    '2017': {
      'SpringWins': 14,
      'SpringTeam': 'Team EnVy',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
      'SummerWins': 21,
      'SummerTeam': 'Team EnVy',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': 6,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 5,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Damonte': {
    'Profile': 'https://lol.gamepedia.com/Damonte',
    'SoloQueueName': 'Damonte',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 1,
      'SummerTeam': 'Echo Fox',
      'SummerTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
    },
    '2018': {
      'SpringWins': 1,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': 7,
      'SummerTeam': 'Echo Fox',
      'SummerTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
    },
    '2019': {
      'SpringWins': 5,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Piglet': {
    'Profile': 'https://lol.gamepedia.com/Piglet',
    'SoloQueueName': 'SKT T1 Piglet',
    '2017': {
      'SpringWins': 17,
      'SpringTeam': 'Team Liquid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_Liquid',
      'SummerWins': 13,
      'SummerTeam': 'Team Liquid',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_Liquid',
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 0,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 5,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Vulcan': {
    'Profile': 'https://lol.gamepedia.com/Vulcan_(Philippe_Laflamme)',
    'SoloQueueName': 'Vulcan',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 0,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 5,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Darshan': {
    'Profile': 'https://lol.gamepedia.com/Darshan',
    'SoloQueueName': 'Darshan',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 6,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Wiggily': {
    'Profile': 'https://lol.gamepedia.com/Wiggily',
    'SoloQueueName': 'Wiggily',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 2,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PowerOfEvil': {
    'Profile': 'https://lol.gamepedia.com/PowerOfEvil',
    'SoloQueueName': 'PowerOfEvil',
    '2017': {
      'SpringWins': 19,
      'SpringTeam': 'Misfits Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Misfits_Gaming',
      'SummerWins': 14,
      'SummerTeam': 'Misfits Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Misfits_Gaming',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'OpTic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/OpTic_Gaming',
      'SummerWins': 9,
      'SummerTeam': 'OpTic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/OpTic_Gaming',
    },
    '2019': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Stixxay': {
    'Profile': 'https://lol.gamepedia.com/Stixxay',
    'SoloQueueName': 'Stixxay',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 7,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Biofrost': {
    'Profile': 'https://lol.gamepedia.com/Biofrost',
    'SoloQueueName': 'Biofrost',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'Team SoloMid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
      'SummerWins': 30,
      'SummerTeam': 'Team SoloMid',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 7,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 21 through 30
  --------------------------------------------- */
  'Solo': {
    'Profile': 'https://lol.gamepedia.com/Solo_(Colin_Earnest)',
    'SoloQueueName': 'Solo',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': 6,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 8,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Rush': {
    'Profile': 'https://lol.gamepedia.com/Rush',
    'SoloQueueName': 'Chimpion',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 4,
      'SummerTeam': 'KT Rolster',
      'SummerTeamLink': 'https://lol.gamepedia.com/KT_Rolster',
    },
    '2019': {
      'SpringWins': 8,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Fenix': {
    'Profile': 'https://lol.gamepedia.com/Fenix',
    'SoloQueueName': 'Fenix',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': 4,
      'SummerTeam': 'Echo Fox',
      'SummerTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
    },
    '2019': {
      'SpringWins': 8,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Apollo': {
    'Profile': 'https://lol.gamepedia.com/Apollo_(Apollo_Price)',
    'SoloQueueName': 'Apollo',
    '2017': {
      'SpringWins': 14,
      'SpringTeam': 'Team EnVy',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
      'SummerWins': 21,
      'SummerTeam': 'Team EnVy',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': 6,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 8,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Hakuho': {
    'Profile': 'https://lol.gamepedia.com/Hakuho',
    'SoloQueueName': 'Hakuho',
    '2017': {
      'SpringWins': 14,
      'SpringTeam': 'Team EnVy',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
      'SummerWins': 21,
      'SummerTeam': 'Team EnVy',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Clutch Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
      'SummerWins': 6,
      'SummerTeam': 'Clutch Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Clutch_Gaming',
    },
    '2019': {
      'SpringWins': 8,
      'SpringTeam': 'Echo Fox',
      'SpringTeamLink': 'https://lol.gamepedia.com/Echo_Fox',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'V1per': {
    'Profile': 'https://lol.gamepedia.com/V1per',
    'SoloQueueName': 'V1per',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2019': {
      'SpringWins': 10,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Santorin': {
    'Profile': 'https://lol.gamepedia.com/Santorin',
    'SoloQueueName': 'Santorin',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 1,
      'SpringTeam': 'H2k-Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/H2k-Gaming',
      'SummerWins': 10,
      'SummerTeam': 'FlyQuest',
      'SummerTeamLink': 'https://lol.gamepedia.com/FlyQuest',
    },
    '2019': {
      'SpringWins': 9,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Pobelter': {
    'Profile': 'https://lol.gamepedia.com/Pobelter',
    'SoloQueueName': 'Pobelter',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Immortals',
      'SpringTeamLink': 'https://lol.gamepedia.com/Immortals',
      'SummerWins': 31,
      'SummerTeam': 'Immortals',
      'SummerTeamLink': 'https://lol.gamepedia.com/Immortals',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Team Liquid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_Liquid',
      'SummerWins': 12,
      'SummerTeam': 'Team Liquid',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_Liquid',
    },
    '2019': {
      'SpringWins': 10,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'WildTurtle': {
    'Profile': 'https://lol.gamepedia.com/WildTurtle',
    'SoloQueueName': 'WildTurtle',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'Team SoloMid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
      'SummerWins': 17,
      'SummerTeam': 'FlyQuest',
      'SummerTeamLink': 'https://lol.gamepedia.com/FlyQuest',
    },
    '2018': {
      'SpringWins': 6,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': 10,
      'SummerTeam': 'FlyQuest',
      'SummerTeamLink': 'https://lol.gamepedia.com/FlyQuest',
    },
    '2019': {
      'SpringWins': 10,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'JayJ': {
    'Profile': 'https://lol.gamepedia.com/JayJ',
    'SoloQueueName': 'JayJ',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 2,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': 9,
      'SummerTeam': 'FlyQuest',
      'SummerTeamLink': 'https://lol.gamepedia.com/FlyQuest',
    },
    '2019': {
      'SpringWins': 10,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 31 through 40
  --------------------------------------------- */
  'Hauntzer': {
    'Profile': 'https://lol.gamepedia.com/Hauntzer',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 41 through 50
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
};

/* ---------------------------------------------
// LINKS
--------------------------------------------- */
// https://www.esportspedia.com/lol/LCS_2019_Spring
// https://www.esportspedia.com/lol/LCS_2019_Summer
// https://www.esportspedia.com/lol/NA_LCS_2018_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2018_Summer_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Summer_Split
