// import playerDataCSV from './LoLProWinsApp-StaticWinsData.csv';

// export const playersData = () => {
//   const lines = playerDataCSV.split('\n');
//   const lcsProPlayers = [];
//   const headers = lines[0].split(',');

//   for(let i = 1; i < lines.length; i++) {
//     const obj = {};
//     const currentline = lines[i].split(',');

//     for(let j = 0; j < headers.length; j++) {
//       obj[headers[j]] = currentline[j];
//     }

//     lcsProPlayers.push(obj);
//   }

//   return (lcsProPlayers); //JavaScript array
//   // return (JSON.stringify(lcsProPlayers)); //JSON
// }

export const proPlayers = {
  /* ---------------------------------------------
  // 1 through 10
  --------------------------------------------- */
  'Ssumday': {
    'Profile': 'https://lol.gamepedia.com/Ssumday',
    'SoloQueueName': 'Ssumdayday',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Team Dignitas',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
      'SummerWins': 29,
      'SummerTeam': 'Team Dignitas',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
    },
    '2018': {
      'SpringWins': 13,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 12,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'AnDa': {
    'Profile': 'https://lol.gamepedia.com/AnDa',
    'SoloQueueName': 'AnDa',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 6,
      'SpringTeam': 'FlyQuest',
      'SpringTeamLink': 'https://lol.gamepedia.com/FlyQuest',
      'SummerWins': 8,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Huhi': {
    'Profile': 'https://lol.gamepedia.com/Huhi',
    'SoloQueueName': 'huhi',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 7,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 7,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Bang': {
    'Profile': 'https://lol.gamepedia.com/Bang',
    'SoloQueueName': '100T Bang',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'SK Telecom T1',
      'SpringTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
      'SummerWins': 26,
      'SummerTeam': 'SK Telecom T1',
      'SummerTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
    },
    '2018': {
      'SpringWins': 23,
      'SpringTeam': 'SK Telecom T1',
      'SpringTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
      'SummerWins': 19,
      'SummerTeam': 'SK Telecom T1',
      'SummerTeamLink': 'https://lol.gamepedia.com/SK_Telecom_T1',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Aphromoo': {
    'Profile': 'https://lol.gamepedia.com/Aphromoo',
    'SoloQueueName': 'aphromoo',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Counter Logic Gaming',
      'SpringTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
      'SummerWins': 27,
      'SummerTeam': 'Counter Logic Gaming',
      'SummerTeamLink': 'https://lol.gamepedia.com/Counter_Logic_Gaming',
    },
    '2018': {
      'SpringWins': 13,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 12,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Licorice': {
    'Profile': 'https://lol.gamepedia.com/Licorice',
    'SoloQueueName': 'Licorice',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 11,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Svenskeren': {
    'Profile': 'https://lol.gamepedia.com/Svenskeren',
    'SoloQueueName': 'Paradiser',
    '2017': {
      'SpringWins': 32,
      'SpringTeam': 'Team SoloMid',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
      'SummerWins': 30,
      'SummerTeam': 'Team SoloMid',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_SoloMid',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 3,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Nisqy': {
    'Profile': 'https://lol.gamepedia.com/Nisqy',
    'SoloQueueName': 'C9 Nisqyyy',
    '2017': {
      'SpringWins': 5,
      'SpringTeam': 'Team EnVy',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
      'SummerWins': 11,
      'SummerTeam': 'Team EnVy',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_EnVyUs',
    },
    '2018': {
      'SpringWins': 11,
      'SpringTeam': 'Splyce',
      'SpringTeamLink': 'https://lol.gamepedia.com/Splyce',
      'SummerWins': 9,
      'SummerTeam': 'Splyce',
      'SummerTeamLink': 'https://lol.gamepedia.com/Splyce',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Sneaky': {
    'Profile': 'https://lol.gamepedia.com/Sneaky',
    'SoloQueueName': 'C9 Sneaky',
    '2017': {
      'SpringWins': 31,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 28,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2018': {
      'SpringWins': 12,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': 10,
      'SummerTeam': 'Cloud 9',
      'SummerTeamLink': 'https://lol.gamepedia.com/Cloud9',
    },
    '2019': {
      'SpringWins': 13,
      'SpringTeam': 'Cloud 9',
      'SpringTeamLink': 'https://lol.gamepedia.com/Cloud9',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'Zeyzal': {
    'Profile': 'https://lol.gamepedia.com/Zeyzal',
    'SoloQueueName': 'Zeyzal',
    '2017': {
      'SpringWins': null,
      'SpringTeam': null,
      'SpringTeamLink': null,
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 11 through 20
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 21 through 30
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 31 through 40
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  /* ---------------------------------------------
  // 41 through 50
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': null,
      'SummerTeam': null,
      'SummerTeamLink': null,
    },
  },
};

/* ---------------------------------------------
// LINKS
--------------------------------------------- */
// https://www.esportspedia.com/lol/LCS_2019_Spring
// https://www.esportspedia.com/lol/LCS_2019_Summer
// https://www.esportspedia.com/lol/NA_LCS_2018_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2018_Summer_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Summer_Split
