export const proPlayers = {
  /* ---------------------------------------------
  // 1 through 10
  --------------------------------------------- */
  'Ssumday': {
    'Profile': 'https://lol.gamepedia.com/Ssumday',
    'SoloQueueName': 'Ssumdayday',
    '2017': {
      'SpringWins': 22,
      'SpringTeam': 'Team Dignitas',
      'SpringTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
      'SummerWins': 29,
      'SummerTeam': 'Team Dignitas',
      'SummerTeamLink': 'https://lol.gamepedia.com/Team_Dignitas',
    },
    '2018': {
      'SpringWins': 13,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 12,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
    '2019': {
      'SpringWins': 4,
      'SpringTeam': '100 Thieves',
      'SpringTeamLink': 'https://lol.gamepedia.com/100_Thieves',
      'SummerWins': 0,
      'SummerTeam': '100 Thieves',
      'SummerTeamLink': 'https://lol.gamepedia.com/100_Thieves',
    },
  },
  'AnDa': {
    'Profile': 'https://lol.gamepedia.com/AnDa',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  /* ---------------------------------------------
  // 11 through 20
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  /* ---------------------------------------------
  // 21 through 30
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  /* ---------------------------------------------
  // 31 through 40
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  /* ---------------------------------------------
  // 41 through 50
  --------------------------------------------- */
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
  'PlayerName': {
    'Profile': 'https://lol.gamepedia.com/',
    'SoloQueueName': 'name',
    '2017': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2018': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
    '2019': {
      'SpringWins': 0,
      'SpringTeam': 'Team Name',
      'SpringTeamLink': 'https://lol.gamepedia.com/',
      'SummerWins': 0,
      'SummerTeam': 'Team Name',
      'SummerTeamLink': 'https://lol.gamepedia.com/',
    },
  },
};

/* ---------------------------------------------
// LINKS
--------------------------------------------- */
// https://www.esportspedia.com/lol/LCS_2019_Spring
// https://www.esportspedia.com/lol/LCS_2019_Summer
// https://www.esportspedia.com/lol/NA_LCS_2018_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2018_Summer_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Spring_Split
// https://www.esportspedia.com/lol/NA_LCS_2017_Summer_Split
